### ISSUE TITLE
Filtrar por URNs legislativas e baixar todos os anos, é possível?

### ISSUE THREAD

**Issue by ppKrauss** [netoferraz/py-lexml-acervo#2]
Olá,  fiz alguns rápidos experimentos navegando pela sua instância de *kaggle*.  Gostaria de entender melhor os objetivos do _py-lexml-acervo_, ou talvez entender melhor como fazer "query de download" para aquilo que desejo recuperar.

Baixando por exemplo [1500-1799](https://www.kaggle.com/lexmlacervo/lexml-brasil-acervo/data?select=1500-1799) obtive um zip com dezenas de zips dentro dele, depois dezenas de pastas.. para no final encontrar um JSON com apenas um item, e que não era de documento legislativo.

```json
[
{"tipoDocumento": "Livro", 
 "facet-tipoDocumento": "Doutrina::Livro", 
 "data": "1556", 
 "urn": "urn:lex:br:rede.virtual.bibliotecas:livro:1556;000104886", 
 "url": "https://www.lexml.gov.br/urn/urn:lex:br:rede.virtual.bibliotecas:livro:1556;000104886",
 "localidade": null, "facet-localidade": null, "autoridade": null, "facet-autoridade": null, 
 "title": "Orationi di m.t. Cicerone di latine fatte italiane", 
 "description": "Sumário:v. 2. Oratione per T. Annio Milone.", 
 "type": "html", 
 "identifier": "008040208"
}
]
```

Estou supondo que haja como filtrar as [URN LEX](https://pt.wikipedia.org/wiki/Lex_(URN)) relativas a documentos legislativos, ou seja, para recuperar metadados de normas (leis, decretos, etc.). Baixando por exemplo 2019 veio um grande JSON e dentro dele pareciam haver normas, mas também haviam projetos de lei.

"Baixar tudo" para mim é interessante pois alimentaria o PostgreSQL, que entende de JSON e me permite redistribuir conforme o modelo de dados desejado (por exemplo uma URN LEX por registro ou agrupando por jurisdição/autoridade).

**Comment by netoferraz** [comment]
Boa noite @ppKrauss. Vamos tentar responder alguns de suas perguntar e/ou dúvidas.

> Gostaria de entender melhor os objetivos do py-lexml-acervo

Esse pacote é uma interface em python para consulta aos dados do acervo do projeto LexML.

> Baixando por exemplo 1500-1799 obtive um zip com dezenas de zips dentro dele, depois dezenas de pastas.. para no final encontrar um JSON com apenas um item, e que não era de documento legislativo.

Se o seu objetivo é ter acesso aos corpo do texto dos normativos, o py-lexml-acervo, e por consequência, nem a [API do LexML](https://www12.senado.leg.br/dados-abertos/legislativo/legislacao/acervo-do-portal-lexml) lhe dará isso diretamente. O projeto LexML serve como um repositório que mapeia a url de origem dos normativos, portanto, as URNs poderão lhe ajudar a criar um crawler para obter esses dados.

> Gostaria de entender melhor os objetivos do py-lexml-acervo, ou talvez entender melhor como fazer "query de download" para aquilo que desejo recuperar.

Esse pacote apesar de realizar uma abstração da consulta à API, as querys ainda necessitão ser escritas no padrão [SRU 1.1](http://www.loc.gov/standards/sru/sru-1-1.html#encoding). Confesso, que não tenho muita familiaridade com esse padrão, vou vou lhe dá alguns exemplos.

Vamos considerar a seguinte urn: **urn:lex:br:federal:decreto:2019-08-16;9975**

Como obter os metadados referente a essa urn? A documentação do padrão SRU informa que alguns caracteres precisam ser representados por uma codificação url, por exemplo, o caractere aspas (") deve ser representado como **%22**. Portanto, o endpoint para recuperar essa urn é:

https://www.lexml.gov.br/busca/SRU?operation=searchRetrieve&query=urn+=%22decreto+federal+2019+08+16+9975%22

No código do py-lexml-acervo:

`urn_query = LexmlAcervo("urn+=\"decreto+federal+2019+08+16+9975\"")`

Outro exemplo, para a urn:

**urn:lex:br:tribunal.superior.trabalho;turma.3:acordao;airr:2011-04-06;108800-2008-40-1-0**
`
query_tst = LexmlAcervo("urn+=\"tribunal.superior.trabalho+turma.3+airr+2011+04+06+108800+2008+40+1+0\"")`

Espero ter lhe ajudado @ppKrauss.

**Comment by netoferraz** [comment]
Vou dar por encerrado a dúvida. Fechando a issue.
